name: arquitetura-hexagonal
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.13"
      - run: go version
      - run: go mod tidy
      - run: cd application
      - run: go test
